name: webview_flutter_plus
description: An extension of webview_flutter to load HTML,CSS and Javascript even from Assets or Strings and much more.
version: 0.1.1+2
homepage: https://github.com/shah-xad/webview_flutter_plus

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.20+2
  mime: ^0.9.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter